apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler

metadata:
  name: goserver-hpa

spec:
  # listen the deployment
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver

  # in production we need at least 3
  minReplicas: 1 
  maxReplicas: 5

  # in production we can use somethin arout 70
  targetCPUUtilizationPercentage: 20