apiVersion: v1
kind: Service
metadata:
  name: goserver-service

spec:
  selector:
    # get all pods thas has app: goserver in label metadata
    # all pods that matches this statment will make part of this service
    app: goserver
  
  # we have 4 types of services: ClusterIP, NodePort, LoadBalancer and headless
  type: ClusterIP
  ports:
    - name: goserver-service
      port: 80 # port that we are going to access when call the svc
      targetPort: 4000 # default 80, container port
      protocol: TCP
