---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mydb-mysql
  namespace: "default"
  labels:
    app.kubernetes.io/name: mysql
    helm.sh/chart: mysql-9.2.4
    app.kubernetes.io/instance: mydb
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: "eTNaeGNRNU1NQQ=="
  mysql-password: "b0VSY2E0eGkwOA=="
