apiVersion: apps/v1
kind: Deployment

metadata:
  name: goserver
  labels:
    app: goserver
  
spec:
  selector: 
    matchLabels:
      app: goserver
  replicas: 1

  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      serviceAccount: server-sa # associate with the service account we created
      containers:
        - name: "goserver"
          image: gbrotas/go-hello:v9
          resources:
            requests: 
              cpu: "0.3" 
              memory: 20Mi 
            limits: 
              cpu: "0.3"
              memory: 25Mi

          ports:
            - containerPort: 4000