apiVersion: v1
kind: ServiceAccount

metadata:
  name: server-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role # namespace role
# kind: ClusterRole # cluster role
metadata:
  name: server-sa-read
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "watch", "list"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-sa-read-bind
subjects:
  - kind: ServiceAccount
    name: server-sa
    namespace: dev # this is going to work to the namespace dev
roleRef:
  kind: Role # namespace role
  # kind: ClusterRole  # cluster role
  name: server-sa-read
  apiGroup: rbac.authorization.k8s.io